export default [
    {   
        id:1,
        Nom: 'Canapé 2 places',
        Volumes: 2,
        nombreFou: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:2,
        Nom: 'Canapé 3 places',
        Volumes: 4,
        nombreFou: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:3,
        Nom: 'Canapé 1 place',
        Volumes: 1,
        nombreFou: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:4,
        Nom: 'Table basse',
        Volumes: 1.5,
        nombreFou: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:5,
        Nom: 'Television',
        Volumes: 0.5,
        nombreFou: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:6,
        Nom: 'Table de Cuisine ',
        Volumes: 3,
        nombreFou: 0,
        image: '...',
        Categorie:'Cuisine',
    },
    {   id:7,
        Nom: 'Chaise',
        Volumes: 0.2,
        nombreFou: 0,
        image: '...',
        Categorie:'Cuisine',
    },  
    {   id:8,
        Nom: 'Buffets',
        Volumes: 3,
        nombreFou: 0,
        image: '...',
        Categorie:'Cuisine',
    },  
    {   id:9,
        Nom: 'Four',
        Volumes: 1,
        nombreFou: 0,
        image: '...',
        Categorie:'Cuisine',
    },  
    {   id:10,
        Nom: 'Micro onde',
        Volumes: 0.3,
        nombreFou: 0,
        image: '...',
        Categorie:'Cuisine',
    },  
    {   id:11,
        Nom: 'Table de Jardin',
        Volumes: 2,
        nombreFou: 0,
        image: '...',
        Categorie:'Jardin',
    },  
    {   id:12,
        Nom: 'Lit 2 places',
        Volumes: 3,
        nombreFou: 0,
        image: '...',
        Categorie:'Chambre',
    },  
    {   id:13,
        Nom: 'Commode ',
        Volumes: 1,
        nombreFou: 0,
        image: '...',
        Categorie:'Chambre',
    },  
    {   id:14,
        Nom: 'Velo',
        Volumes: 1,
        nombreFou: 0,
        image: '...',
        Categorie:'Garage',
    },  
    {   id:15,
        Nom: 'Machine a laver',
        Volumes: 2,
        nombreFou: 0,
        image: '...',
        Categorie:'Salle de bain',
    },  
    {   id:16,
        Nom: 'Séche linge',
        Volumes: 1,
        nombreFou: 0,
        image: '...',
        Categorie:'Salle de bain',
    },  
    {   id:17,
        Nom: 'Quad',
        Volumes: 3,
        nombreFou: 0,
        image: '...',
        Categorie:'Garage',
    },  
    {   id:18,
        Nom: 'Carton',
        Volumes: 0.5,
        nombreFou: 0,
        image: '...',
        Categorie:'Divers',
    },  
    {   id:19,
        Nom: 'Bibliotheque',
        Volumes: 3,
        nombreFou: 0,
        image: '...',
        Categorie:'Salon',
    }
];