export default [
    {   
        id:1,
        Nom: 'Canapé 2 places',
        Volumes: 2,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:2,
        Nom: 'Canapé 3 places',
        Volumes: 4,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:3,
        Nom: 'Canapé 1 place',
        Volumes: 1,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:4,
        Nom: 'Table basse',
        Volumes: 1.5,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:5,
        Nom: 'Television',
        Volumes: 0.5,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   id:6,
        Nom: 'Table de cuisine ',
        Volumes: 3,
        Quantité: 0,
        image: '...',
        Categorie:'cuisine',
    },
    {   id:7,
        Nom: 'chaise de cuisine',
        Volumes: 0.2,
        Quantité: 0,
        image: '...',
        Categorie:'cuisine',
    },  
    {   id:8,
        Nom: 'Buffets',
        Volumes: 3,
        Quantité: 0,
        image: '...',
        Categorie:'cuisine',
    },  
    {   id:9,
        Nom: 'Four',
        Volumes: 1,
        Quantité: 0,
        image: '...',
        Categorie:'cuisine',
    },  
    {   id:10,
        Nom: 'Micro onde',
        Volumes: 0.3,
        Quantité: 0,
        image: '...',
        Categorie:'cuisine',
    },  
    {   id:11,
        Nom: 'Table de jardin',
        Volumes: 2,
        Quantité: 0,
        image: '...',
        Categorie:'jardin',
    },  
    {   id:12,
        Nom: 'Lit 2 places',
        Volumes: 3,
        Quantité: 0,
        image: '...',
        Categorie:'chambre',
    },  
    {   id:13,
        Nom: 'Commode ',
        Volumes: 1,
        Quantité: 0,
        image: '...',
        Categorie:'chambre',
    },  
    {   id:14,
        Nom: 'velo',
        Volumes: 1,
        Quantité: 0,
        image: '...',
        Categorie:'garage',
    },  
    {   id:15,
        Nom: 'Machine a laver',
        Volumes: 2,
        Quantité: 0,
        image: '...',
        Categorie:'Salle de bain',
    },  
    {   id:16,
        Nom: 'séche linge',
        Volumes: 1,
        Quantité: 0,
        image: '...',
        Categorie:'Salle de bain',
    },  
    {   id:17,
        Nom: 'quad',
        Volumes: 3,
        Quantité: 0,
        image: '...',
        Categorie:'garage',
    },  
    {   id:18,
        Nom: 'Carton',
        Volumes: 0.5,
        Quantité: 0,
        image: '...',
        Categorie:'divers',
    },  
    {   id:19,
        Nom: 'Bibliotheque',
        Volumes: 3,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    }
];