const datasFournitures = 
[
    {   Nom: 'Canapé 2 places',
        Volumes: 2,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   Nom: 'Canapé 3 places',
        Volumes: 4,
        Quantité: 0,
        image: '...',
        Categorie:'Salon',
    },
    {   Nom: 'Canapé 1 place',
    Volumes: 1,
    Quantité: 0,
    image: '...',
    Categorie:'Salon',
    },
    {   Nom: 'Table basse',
    Volumes: 1.5,
    Quantité: 0,
    image: '...',
    Categorie:'Salon',
    },
    {   Nom: 'Television',
    Volumes: 0.5,
    Quantité: 0,
    image: '...',
    Categorie:'Salon',
    },
    {   Nom: 'Table de cuisine ',
    Volumes: 3,
    Quantité: 0,
    image: '...',
    Categorie:'cuisine',
    },
    {   Nom: 'chaise de cuisine',
    Volumes: 0.2,
    Quantité: 0,
    image: '...',
    Categorie:'cuisine',
    },  
    {   Nom: 'Buffets',
    Volumes: 3,
    Quantité: 0,
    image: '...',
    Categorie:'cuisine',
    },  
    {   Nom: 'Four',
    Volumes: 1,
    Quantité: 0,
    image: '...',
    Categorie:'cuisine',
    },  
    {   Nom: 'Micro onde',
    Volumes: 0.3,
    Quantité: 0,
    image: '...',
    Categorie:'cuisine',
    },  
    {   Nom: 'Table de jardin',
    Volumes: 2,
    Quantité: 0,
    image: '...',
    Categorie:'jardin',
    },  
    {   Nom: 'Lit 2 places',
    Volumes: 3,
    Quantité: 0,
    image: '...',
    Categorie:'chambre',
    },  
    {   Nom: 'Commode ',
    Volumes: 1,
    Quantité: 0,
    image: '...',
    Categorie:'chambre',
    },  
    {   Nom: 'velo',
    Volumes: 1,
    Quantité: 0,
    image: '...',
    Categorie:'garage',
    },  
    {   Nom: 'Machine a laver',
    Volumes: 2,
    Quantité: 0,
    image: '...',
    Categorie:'Salle de bain',
    },  
    {   Nom: 'séche linge',
    Volumes: 1,
    Quantité: 0,
    image: '...',
    Categorie:'Salle de bain',
    },  
    {   Nom: 'quad',
    Volumes: 3,
    Quantité: 0,
    image: '...',
    Categorie:'garage',
    },  
    {   Nom: 'Carton',
    Volumes: 0.5,
    Quantité: 0,
    image: '...',
    Categorie:'divers',
    },  
    {   Nom: 'Bibliotheque',
    Volumes: 3,
    Quantité: 0,
    image: '...',
    Categorie:'Salon',
    }
];